use_frameworks!

platform :ios, '8.0'

target 'DLNAWrapper_Example' do
  pod 'DLNAWrapper', :path => '../'

  target 'DLNAWrapper_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
